FROM kalilinux/kali-rolling:arm64@sha256:b6d14c844ded8ef62de2c93d46668b348b18b3a84b2837a3c25f22d8b5cdbcd1

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2025.4.7

RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=${KALI_META_VERSION} kali-linux-default=${KALI_META_VERSION} kali-tools-web=${KALI_META_VERSION} \
  && rm -rf /var/lib/apt/lists/*
