FROM kalilinux/kali-rolling:armhf@sha256:3bef8837058da34337d4b5cf3fca5dbddf0cc5bc23ffc4e2fc2d9dbb41673d0d

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2026.1.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=${KALI_META_VERSION} kali-linux-default=${KALI_META_VERSION} kali-tools-web=${KALI_META_VERSION} \
  && rm -rf /var/lib/apt/lists/*
