FROM kalilinux/kali-rolling:amd64@sha256:f63df9046d2532c07e6f2d6eeeb7f2bc4ac8352b9af326f5a1141926d23f9647

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2026.1.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=${KALI_META_VERSION} kali-linux-default=${KALI_META_VERSION} kali-tools-web=${KALI_META_VERSION} \
  && rm -rf /var/lib/apt/lists/*
