FROM kalilinux/kali-rolling:i386@sha256:744f7de03096a73b2f0704b4d81ac64dde9658bf81e4d5609aa0c5b02b95ebab

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2026.1.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=${KALI_META_VERSION} kali-linux-default=${KALI_META_VERSION} kali-tools-web=${KALI_META_VERSION} \
  && rm -rf /var/lib/apt/lists/*
