FROM kalilinux/kali-rolling:amd64@sha256:45eeb73d6f144a6a2fcf699b849c1d72ff5f2007ec952c98ab3084b77e9114a5

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2026.1.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=${KALI_META_VERSION} kali-linux-default=${KALI_META_VERSION} kali-tools-web=${KALI_META_VERSION} \
  && rm -rf /var/lib/apt/lists/*
