FROM kalilinux/kali-rolling:armhf@sha256:59f097895c5a49cdeaed2ea59330057fb7c6bd29c35b1b6bae9f0d35a7c48be7

# Install the tools
# renovate: datasource=repology depName=kali_rolling/kali-meta versioning=loose
ENV KALI_META_VERSION=2026.1.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=${KALI_META_VERSION} kali-linux-default=${KALI_META_VERSION} kali-tools-web=${KALI_META_VERSION} \
  && rm -rf /var/lib/apt/lists/*
