FROM kalilinux/kali-rolling:armhf@sha256:05c56fa6eae4952002b648482d0c3a50efa3fca729d93cb58bc5398242b4812e

# Install the tools
RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=2025.1.2 kali-linux-default=2025.1.2 kali-tools-web=2025.1.2 \
  && rm -rf /var/lib/apt/lists/*
