FROM kalilinux/kali-rolling:amd64@sha256:4c516126b5ef76dbf1423366853862c0d885e3d3d8f02fd0ab966cce1c6e11ab

# Install the tools
RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core==2025.1.2 kali-linux-default==2025.1.2 kali-tools-web==2025.1.2 \
  && rm -rf /var/lib/apt/lists/*
