FROM kalilinux/kali-rolling:i386@sha256:343332fbc0006e521a7a256152ec6adcc7a3440c74246b072c270ccdf2561135

# Install the tools
RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=2025.1.2 kali-linux-default=2025.1.2 kali-tools-web=2025.1.2 \
  && rm -rf /var/lib/apt/lists/*
