FROM kalilinux/kali-rolling:amd64@sha256:c1c7d84e57939389a95cc385879c7e5231e77e296b40436bb06748972e4bb615

# Install the tools
RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core==2025.1.2 kali-linux-default==2025.1.2 kali-tools-web==2025.1.2 \
  && rm -rf /var/lib/apt/lists/*
