FROM kalilinux/kali-rolling:armel@sha256:87609414fe53a2709a638a1e37af66ded196fa8a98e73efa1a136e62fc351c36

# Install the tools
RUN apt-get update \
  && apt-get install -y --no-install-recommends kali-linux-core=2025.1.2 kali-linux-default=2025.1.2 kali-tools-web=2025.1.2 \
  && rm -rf /var/lib/apt/lists/*
