FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim@sha256:e5b65587bce7de595f299855d7385fe7fca39b8a74baa261ba1b7147afa78e58

WORKDIR /app

COPY pyproject.toml .
RUN uv sync --no-dev --no-install-project

COPY main.py .

CMD ["uv", "run", "main.py"]
