name: PR CI
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
permissions:
  pull-requests: read
jobs:
  pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        with:
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
